### ISSUE TITLE
Asynchronous execution not functioning

### ISSUE THREAD

**Issue by KyleGershman** [eapowertools/QlikSenseTask#16]
Per the instructions, I omit the -wait parameter, but despite having removed the default -wait from config.txt, the default remains 600 seconds.  If I put the parameter -wait:0, it has the desired effect of an asynchronous task submission, but does finish with Error Level 8.  Using debug and overriding timeout to 0 will then give Error Level 4.

Ideally, it would honor the lack of the -wait parameter and consider it a successful execution even if it's simply to kick off a Task.

**Comment by KyleGershman** [comment]
A small edit worked for me, passing -wait:0 as a parameter:
                logger.Log(LogLevel.Information, "Task is starting...");
                QlikSenseTaskExecutionGuid taskexecutionguid = qs.StartTaskByName(task, synchronous);

                if (timeout == 0)
                {
                    logger.Log(LogLevel.Information, "Task submitted asynchronously...");
                    logger.End();
                    Environment.Exit(retval);
                }

**Comment by marcusspitzmiller** [comment]
oh, we overlapped notes.  i did it a little differently but the result should be the same

**Comment by KyleGershman** [comment]
It's giving me error level 4, which is what I got when I did make sure that a -wait:0 parameter set the timeout global to 0.

qliksensetask -proxy:"https://localhost" -task:"Test Task" -wait:0

**Comment by marcusspitzmiller** [comment]
d'oh.  it would help if i committed the code change.  try now.

**Comment by KyleGershman** [comment]
Still having a challenge.  I try it with the full command line so I don't rely on the config.txt (since I noticed it getting pulled in despite my original wish).  I have tried with the config.txt as defaulted and I've tried it renaming the config.txt so only the command line parameters are taken.

The log does show that the wait is 0, which is good...and it still does start the task, but again, it's coming back with Error Level of 4.

**Comment by marcusspitzmiller** [comment]
Hi Kyle, i changed it to use your approach.  Try now.

**Comment by KyleGershman** [comment]
Yes, that works as expected.  Thanks for your rapid response and willingness to adopt.  Will you merge your branches?

**Comment by marcusspitzmiller** [comment]
done
